### ISSUE TITLE
Post data is coming as hex code in curl 

### ISSUE THREAD

**Issue by Chirag008** [dzieciou/curl-logger#25]
A simple POST request is sent with JSON Data. The created curl contains hex code instead of normal text in the request.

For eg. REST ASSURED request was (logs of rest assured)

Request method:	POST
Request URI:	http://dummy.restapiexample.com/api/v1/create?code=1234&name=test22
Proxy:			<none>
Request params:	<none>
Query params:	code=1234
				name=test22
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*
				Content-Type=application/json
Cookies:		<none>
Multiparts:		<none>
Body:
{'name':"CKB2",'salary':'123','age':'23'}

And the curl created was -- 
curl 'http://dummy.restapiexample.com/api/v1/create?code=1234&name=test22' -H 'Accept: */*' -H 'Content-Type: application/json' -H 'Host: dummy.restapiexample.com' -H 'Connection: Keep-Alive' -H 'User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_212)' -d $'\x7b\x27\x6e\x61\x6d\x65\x27\x3a\x22\x43\x4b\x42\x32\x22\x2c\x27\x73\x61\x6c\x61\x72\x79\x27\x3a\x27\x31\x32\x33\x27\x2c\x27\x61\x67\x65\x27\x3a\x27\x32\x33\x27\x7d' --compressed -k -v

I suppose, instead of hex data, it should appear in normal text.

**Comment by dzieciou** [comment]
Looking into it. Thanks for the report.

**Comment by dzieciou** [comment]
The library was applying ANSI C Quoting (including escaping characters as hex codes) to all characters, even if only some of them required escaping. That was definitely too strict. In your case only single quote required escaping. Still I need to escape some characters, because the generated curl command will be copy-pasted on a multitude of setups by a wide range of people. I don't want the result to vary based on people's local encoding or misconfigured terminals.

Therefore, I have changed the way characters are escaped in the generated curl command.

For POSIX use [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html), in particular
  * escape non-printable ASCII characters either with additional backslash (`\n` will become `\\n`) or hex code 
  * escape single quote `'` and at character `@` with backslash, because they have special meaning in curl
  * by default, escape non-ASCII characters with hex, e.g., 'name=Administração' will become $'name=Administra\xe7\xe3o' (this can be disabled through `Options#disableEscapeNonAscii`).

For Window, I kept it as it was.

Also, all data are now passed through `--data-binary` instead of `--data` curl parameter, because the latter strips newline (`\n`) and carriage return (`\r`) characters. To reproduce server problems I want the requested sent be the general curl command to be as identical to original request as possible.

**Comment by dzieciou** [comment]
If you want to try the fix, it's available in the branch. I will keep it for some time in a branch and then in 1.0.5-SNAPSHOT version before it is really, because the change was quite significant and I want to make sure it has not affected other areas.
