### ISSUE TITLE
Wrong decoding of special characters

### ISSUE THREAD

**Issue by francislainy** [dzieciou/curl-logger#51]
Just noticed that when a field uses special characters they get decoded with what it seems their UTF symbol. Tried a password as P@ssword! for my test user and got P\x40ssword! on the curl logger.

![image](https://user-images.githubusercontent.com/19685849/96148299-0bf5b200-0f00-11eb-81fc-c3b0eb503f35.png)

**Comment by dzieciou** [comment]
That is expected behaviour.

This is example of [ANSI C-Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html):

> Words of the form `$'string'` are treated specially. The word expands to string, with backslash-escaped characters replaced as specified by the ANSI C standard.

In particular, `@` character has a special meaning in `--data-binary` (loading a file). It is escaped with hex value of its ASCII code.

The important thing is that server receives properly serialized strings. For instance, here's what `httpbin` server gets when sending your request:

```bash
curl https://httpbin.org/post  --header 'Accept: application/json' --header 'Content-Type: application/json; charset=UTF-8' --data-binary $'{"id":11044, "password":"P\x40ssword"}'
{
  "args": {}, 
  "data": "{\"id\":11044, \"password\":\"P@ssword\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "application/json", 
    "Content-Length": "35", 
    "Content-Type": "application/json; charset=UTF-8", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.68.0", 
    "X-Amzn-Trace-Id": "Root=1-5f9979d4-7fc1c120091a7a48134c8330"
  }, 
  "json": {
    "id": 11044, 
    "password": "P@ssword"
  }, 
  "origin": "46.204.5.100", 
  "url": "https://httpbin.org/post"
}
```

Is your server receiving incorrectly serialized request?

**Comment by francislainy** [comment]
Yes, my server responded with an error on Postman when I posted the curl generated by the library and that's how I noticed the issue. I'm on a mac.

**Comment by dzieciou** [comment]
Ahh, I guess what's you're doing is trying to [import curl](https://stackoverflow.com/a/37068925/142605) command into Postman, right?

> 1. Open POSTMAN.
> 2. Click on "import" tab on the upper left side.
> 3. Select the Raw Text option and paste your cURL command.
> 4. Hit import and you will have the command in your Postman builder!
> 5. Click Send to post the command.

If so, what happens if you try to run the curl command from the command line instead?

If it works this way it might a bug in Postman when parsing such requests. curl-logger is supposed to generate curl commands to work in command line.

I can see two solutions:

1. Raise this bug to Postman team.
2. Provide an option in curl-logger to not escape "@" in `--data-binary` content.

I am not sure yet if providing such a custom behaviour in the latter solution is good.

**Comment by francislainy** [comment]
Hi, yes, you're right. If I run this on a terminal it works fine but not on Postman.
