### ISSUE TITLE
[Feature Request] Curl2HTTP support

### ISSUE THREAD

**Issue by truebit** [dzieciou/curl-logger#79]
great work for this rest-assured to curl libary.
I would like to convert some curl string to rest-assured requests. where should I start? thanks

**Comment by dzieciou** [comment]
Thanks for the question.

You would need to implement that functionality from scratch.

You would need:
- curl command parser, that can turn curl command string into [`CurlCommand`](https://github.com/dzieciou/curl-logger/blob/master/src/main/java/com/github/dzieciou/testing/curl/CurlCommand.java) object
- code generate that can generate Java source code with RestAssured request from `CurlCommand` object

For parsers you can look at libraries from command line argument parsing: https://stackoverflow.com/questions/367706/how-do-i-parse-command-line-arguments-in-java or add example custom parser for culr commands from JMeter (https://github.com/apache/jmeter/blob/master/src/protocol/http/src/main/java/org/apache/jmeter/protocol/http/curl/BasicCurlParser.java) although I'm not sure if it supports all options.

For code generators there are many libraries based on templates, some mentioned here:
- https://stackoverflow.com/questions/209987/code-template-generator-for-java
- https://stackoverflow.com/questions/5882121/how-to-build-simple-code-generator-in-java

I can imagine any code from the existing library to be helpful for your goal (apart from mentioned `CurlCommand` class). I also think this feature should be rather part of a new library rather than a new feature of this one.

Let me know if you have any further questions.

**Comment by dzieciou** [comment]
Closing.
